name: Export Recommendations JSON

on:
  schedule:
    - cron: "0 * * * *"  # 每小時執行一次（UTC）
  workflow_dispatch:     # 可手動觸發

jobs:
  export-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Fetch recommendations JSON
        run: |
          curl "https://script.google.com/macros/s/AKfycbzdoezSaX2ujsE5ejjac3HbZWWHhDKQbX0nN1rVTIPSZm7opdCtslmwPAIq6zBNvcTp/exec?action=exportJSON" \
            -o data/recommendations.json

      - name: Commit and push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/recommendations.json
          git diff --cached --quiet || git commit -m "⏱️ Update recommendations.json from GAS"
          git push
